name: Discord Canary

on:
  workflow_call:
    secrets:
      PAT:
        required: true
      GPG_PRIVATE_KEY:
        required: true
      GPG_PASSPHRASE:
        required: true

env:
  GIT_NAME: brewcoua-bot
  GIT_EMAIL: 151367391+brewcoua-bot@users.noreply.github.com

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    outputs:
      latest: ${{ steps.latest.outputs.latest }}
      needs_update: ${{ steps.check.outputs.needs_update }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Get latest version
        id: latest
        run: |
          LATEST=$(curl -SsI https://discord.com/api/download/canary\?platform\=linux\&format\=deb | awk '/location/ {print $2}' | awk -F/ '{print $NF}')
          echo "latest=${LATEST}" >> "$GITHUB_OUTPUT"

      - name: Check if the latest version is already in the repo
        id: check
        working-directory: ubuntu/discord-canary
        run: |
          if [ -e "$GITHUB_WORKSPACE/ubuntu/discord-canary/$LATEST" ]; then
            echo "The latest version is already in the repo"
            echo "needs_update=false" >> "$GITHUB_OUTPUT"
          else
            echo "The latest version is not in the repo"
            echo "needs_update=true" >> "$GITHUB_OUTPUT"
          fi

  update:
    name: Update
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.needs_update == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Download the latest version
        env:
          LATEST: ${{ needs.check.outputs.latest }}
        run: |
          curl -SsL https://discord.com/api/download/canary\?platform\=linux\&format\=deb -o "$GITHUB_WORKSPACE/ubuntu/discord-canary/$LATEST"

      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Update index
        working-directory: ubuntu
        run: |
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages

          apt-ftparchive release . > Release
          gpg --default-key "${GIT_EMAIL}" -abs -o - Release > Release.gpg
          gpg --default-key "${GIT_EMAIL}" --clearsign -o - Release > InRelease

      - name: Push the latest version
        env:
          LATEST: ${{ needs.check.outputs.latest }}
        run: |
          git config --global user.name "${GIT_NAME}"
          git config --global user.email "${GIT_EMAIL}"

          git add .
          git commit -m "chore(deb): update discord-canary to $LATEST"
          git push
